// Class BlueprintComponentReference.BlueprintComponentReferenceLibrary
// Size: 0x30 (Inherited: 0x30)
struct UBlueprintComponentReferenceLibrary : UBlueprintFunctionLibrary {

	void TryGetReferencedComponent(struct FBlueprintComponentReference& Reference, struct AActor* Actor, struct UActorComponent* Class, enum class EComponentSearchResult& Result, struct UActorComponent*& Component); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.TryGetReferencedComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x55825e0
	bool Set_ContainsComponent(struct TSet<struct FBlueprintComponentReference>& TargetSet, struct UActorComponent* ItemToFind); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Set_ContainsComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x55809f0
	bool NotEqual_ComponentReference(struct FBlueprintComponentReference& A, struct FBlueprintComponentReference& B); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.NotEqual_ComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5581260
	bool Map_FindComponent(struct TMap<int32_t, int32_t>& TargetMap, struct UActorComponent* Component, int32_t& Value); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Map_FindComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5580500
	bool IsValidComponentReference(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.IsValidComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5581740
	bool IsNullComponentReference(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.IsNullComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5581860
	void InvalidateComponentReference(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.InvalidateComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x5581640
	void GetSetReferencedComponents(struct TSet<struct FBlueprintComponentReference>& References, struct AActor* Actor, struct UActorComponent* Class, struct TSet<struct UActorComponent*>& Components); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.GetSetReferencedComponents // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x5581980
	void GetReferencedComponents(struct TArray<struct FBlueprintComponentReference>& References, struct AActor* Actor, struct UActorComponent* Class, bool bKeepNulls, struct TArray<struct UActorComponent*>& Components); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.GetReferencedComponents // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x5581e50
	bool GetReferencedComponent(struct FBlueprintComponentReference& Reference, struct AActor* Actor, struct UActorComponent* Class, struct UActorComponent*& Component); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.GetReferencedComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5582200
	bool EqualEqual_ComponentReference(struct FBlueprintComponentReference& A, struct FBlueprintComponentReference& B); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.EqualEqual_ComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5581450
	struct FString Conv_ComponentReferenceToString(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Conv_ComponentReferenceToString // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x55810f0
	bool Array_ContainsComponent(struct TArray<struct FBlueprintComponentReference>& TargetArray, struct UActorComponent* ItemToFind); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Array_ContainsComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5580ec0
};

