// BlueprintGeneratedClass CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C
// Size: 0x30 (Inherited: 0x30)
struct UCollectionContentFiltersLibrary_C : UBlueprintFunctionLibrary {

	void SetOrGetContentFilterViewModel(struct FString ModelId, struct TArray<struct UContentFilter*>& FilterClasses, struct UObject* __WorldContext, struct UContentFilterViewModel*& ContentFilterViewModel); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.SetOrGetContentFilterViewModel // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void SetCarouselShowOwnedButton(struct UGenericCarousel_C* Carousel, bool IsContentFilterEnabled, struct UObject* __WorldContext); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.SetCarouselShowOwnedButton // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void MakeContentFilterObjects(struct TArray<struct UContentFilter*>& FilterClasses, struct UObject* __WorldContext, struct TArray<struct UContentFilter*>& ReturnedFilters); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.MakeContentFilterObjects // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void IsFavoriteFilterEnabled(struct UContentFilterViewModel* FilterViewModel, struct UObject* __WorldContext, bool& IsEnabled); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.IsFavoriteFilterEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetFavoriteFilterFromModel(struct UContentFilterViewModel* Model, struct UObject* __WorldContext, struct UFavoritesFilter_C*& FavoriteFilter); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.GetFavoriteFilterFromModel // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void UpdateTabWidgetVisibility(bool HasMatchingContent, struct TArray<struct UWidget*>& WidgetsToHide, struct UWidget* NoResultMessage, struct UObject* __WorldContext); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.UpdateTabWidgetVisibility // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void UpdateFilterModelFromShowOwnedOnly(bool IsShowOwnedOnly, struct UContentFilter* OwnershipFilter, struct UObject* __WorldContext); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.UpdateFilterModelFromShowOwnedOnly // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void ShouldOwnedOnlyFilterBeEnabled(struct UContentFilter* OwnershipFilter, struct UObject* __WorldContext, bool& ShouldBeEnabled); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.ShouldOwnedOnlyFilterBeEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetOwnershipFilterFromModel(struct UContentFilterViewModel* Model, struct UObject* __WorldContext, struct UOwnershipFilter_C*& OwnershipFilter); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.GetOwnershipFilterFromModel // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetOwnershipCriteria(struct UContentFilter* Filter, struct UObject* __WorldContext, struct UOwnedCriterion*& Owned, struct UNotOwnedCriterion*& NotOwned); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.GetOwnershipCriteria // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void ApplyContentFilters(struct UContentFilterViewModel* FilterViewModel, struct TArray<struct UBaseHandle*>& content, struct UGenericCarousel_C* Carousel, bool EnableContentFiltering, bool OverrideOwnershipChangedDispatch, bool PreventOwnershipChangedDispatch, struct UObject* __WorldContext, struct TArray<struct UBaseHandle*>& Filtered); // Function CollectionContentFiltersLibrary.CollectionContentFiltersLibrary_C.ApplyContentFilters // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
};

