// BlueprintGeneratedClass Esports_Functions.Esports_Functions_C
// Size: 0x30 (Inherited: 0x30)
struct UEsports_Functions_C : UBlueprintFunctionLibrary {

	void InitStageWidgetV1(struct UWidget* InWidget, struct UEsportsMatchupTeamViewModel* InTeamViewModel, struct FString InStageName, bool bIsFirstSeed, struct UObject* __WorldContext); // Function Esports_Functions.Esports_Functions_C.InitStageWidgetV1 // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void Setup Stage Placement Widget(struct UUserWidget* Widget, struct FString MatchupID, struct FString AdvancesToStageSlug, struct UEsportsBracketScreenViewModelV2* BracketScreenViewModelV2, struct UEsportsBracketScreenViewModel* BracketScreenViewModel, struct UObject* __WorldContext); // Function Esports_Functions.Esports_Functions_C.Setup Stage Placement Widget // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void SetupStagePlacementWithMatchupVM(struct UWidget* InWidget, struct UEsportsMatchupViewModelV2* InMatchupViewModel, struct FString InStageName, bool bInIsFirstSeed, struct UObject* __WorldContext); // Function Esports_Functions.Esports_Functions_C.SetupStagePlacementWithMatchupVM // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void GetLocalizedRegionAndNameForVCT25Event(enum class E2024VCTEvent VCTEvent, struct UObject* __WorldContext, struct FText& RegionAndEventName); // Function Esports_Functions.Esports_Functions_C.GetLocalizedRegionAndNameForVCT25Event // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void GetLocalizedNameForVCT25Event(enum class E2024VCTEvent VCTEvent, struct UObject* __WorldContext, struct FText& Event Name); // Function Esports_Functions.Esports_Functions_C.GetLocalizedNameForVCT25Event // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void Get Event Status From Date Range(struct FDateTime StartTimeUTC, struct FDateTime EndTimeUTC, struct UObject* __WorldContext, enum class EEsportsMatchStatus& Event Status); // Function Esports_Functions.Esports_Functions_C.Get Event Status From Date Range // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void Format Esports Date Range(struct FDateTime StartTimeUTC, struct FDateTime EndTimeUTC, struct UObject* __WorldContext, struct FText& FormattedDateText); // Function Esports_Functions.Esports_Functions_C.Format Esports Date Range // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void FormatEsportsDateRange_OLD(struct FText InDateText, struct UObject* __WorldContext, struct FText& FormattedDateText); // Function Esports_Functions.Esports_Functions_C.FormatEsportsDateRange_OLD // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void GetColorForEsportsEvent(bool Get Individual Event Color, enum class E2024VCTEvent event, struct UObject* __WorldContext, struct FLinearColor& Color); // Function Esports_Functions.Esports_Functions_C.GetColorForEsportsEvent // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
};

