// BlueprintGeneratedClass OfferUtils.OfferUtils_C
// Size: 0x30 (Inherited: 0x30)
struct UOfferUtils_C : UBlueprintFunctionLibrary {

	void CompareSubOffers(struct TArray<struct UOfferDTO*>& SubOffers1, struct TArray<struct UOfferDTO*>& SubOffers2, struct UObject* __WorldContext, bool& AreEqual); // Function OfferUtils.OfferUtils_C.CompareSubOffers // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CompareBodedgaOffers(struct UOfferDTO* Offer1, struct UOfferDTO* Offer2, struct UObject* __WorldContext, bool& Equal); // Function OfferUtils.OfferUtils_C.CompareBodedgaOffers // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CompareByOfferType(struct UOfferDTO* Offer1, struct UOfferDTO* Offer2, struct UObject* __WorldContext, bool& Equal); // Function OfferUtils.OfferUtils_C.CompareByOfferType // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetInventoryModelFromRewardModel(struct URewardModel* RewardModelObject, struct UObject* __WorldContext, bool& IsValid, struct UBaseInventoryModel*& BaseInventoryModel); // Function OfferUtils.OfferUtils_C.GetInventoryModelFromRewardModel // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CompareOfferDTOs(struct UOfferDTO* OfferA, struct UOfferDTO* OfferB, struct UObject* __WorldContext, bool& AreEqual); // Function OfferUtils.OfferUtils_C.CompareOfferDTOs // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void BreakOfferDTO(struct UOfferDTO* OfferDTO, struct UObject* __WorldContext, bool& IsValid, struct FGuid& OfferId, struct TMap<struct FGuid, struct UCostDTO*>& Costs, struct TArray<struct FGuid>& RewardsList, struct TArray<struct UOfferDTO*>& SubOffersList, enum class EOfferDTOType& OfferType, enum class EGiftingType& GiftableType, bool& IsGift); // Function OfferUtils.OfferUtils_C.BreakOfferDTO // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void BreakCostDTO(struct UCostDTO* CostDTO, struct UObject* __WorldContext, struct FGuid& CurrencyID, int32_t& BaseCost, int32_t& DiscountedCost, int32_t& DiscountPercent); // Function OfferUtils.OfferUtils_C.BreakCostDTO // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void BreakSingleItemOfferDTO(struct UOfferDTO* OfferDTO, struct UObject* __WorldContext, bool& IsValid, struct FGuid& CurrencyID, int32_t& RewardQuantity, int32_t& BaseCost, int32_t& DiscountedCost, int32_t& DiscountPercent, struct URewardModel*& RewardModel, struct UBaseInventoryModel*& InventoryModel); // Function OfferUtils.OfferUtils_C.BreakSingleItemOfferDTO // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetRewardFromSingleItemOfferDTO(struct UOfferDTO* OfferDTO, struct UObject* __WorldContext, bool& IsValid, struct FGuid& ItemId, int32_t& Quantity, struct URewardModel*& RewardModel, struct UBaseInventoryModel*& InventoryModel); // Function OfferUtils.OfferUtils_C.GetRewardFromSingleItemOfferDTO // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetRewardFromSingleItemOffer(struct UStoreOffer* Offer, struct UObject* __WorldContext, bool& IsValid, struct FGuid& ItemId, int32_t& Quantity, struct URewardModel*& RewardModel, struct UBaseInventoryModel*& InventoryModel); // Function OfferUtils.OfferUtils_C.GetRewardFromSingleItemOffer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void Break SingleItemOffer(struct UStoreOffer* Offer, struct UObject* __WorldContext, bool& IsValid, struct FGuid& CurrencyID, int32_t& Quantity, int32_t& Amount, struct URewardModel*& RewardModel, struct UBaseInventoryModel*& InventoryModel); // Function OfferUtils.OfferUtils_C.Break SingleItemOffer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
};

