// BlueprintGeneratedClass PartySharedFunctions.PartySharedFunctions_C
// Size: 0x30 (Inherited: 0x30)
struct UPartySharedFunctions_C : UBlueprintFunctionLibrary {

	void CheckPartyMembersUnverified(struct UPartyModel* Model, struct UObject* __WorldContext, bool& AreAnyMembersUnverified, struct TArray<struct FString>& UnverifiedMembers); // Function PartySharedFunctions.PartySharedFunctions_C.CheckPartyMembersUnverified // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void GetPremierQueueInfoText(struct FString Queue Name, struct UObject* __WorldContext, struct FText& Premier Queue Info Text, bool& Did Succeed); // Function PartySharedFunctions.PartySharedFunctions_C.GetPremierQueueInfoText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void ShouldShowModalForPartyError(struct UPartyErrorNotification* PartyErrorNotification, struct UObject* __WorldContext, bool& Should Show Modal); // Function PartySharedFunctions.PartySharedFunctions_C.ShouldShowModalForPartyError // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	struct UQueuedNotification* HandlePartyErrorNotification(struct UPartyErrorNotification* PartyErrorNotification, struct UObject* __WorldContext); // Function PartySharedFunctions.PartySharedFunctions_C.HandlePartyErrorNotification // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void CreateErrorMessage(struct UPartyErrorNotification* PartyErrorNotification, struct UObject* __WorldContext, struct FText& FormattedErrorMessageText, struct FText& ErrorMessageText); // Function PartySharedFunctions.PartySharedFunctions_C.CreateErrorMessage // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void GetPingStatus(int32_t Ping, struct UAresClientGameInstance* GameInstance, struct UObject* __WorldContext, enum class PartyPingStatus& Status); // Function PartySharedFunctions.PartySharedFunctions_C.GetPingStatus // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void GetColorFromPing(struct UAresClientGameInstance* GameInstance, int32_t Ping, struct UObject* __WorldContext, struct FLinearColor& ColorToUse); // Function PartySharedFunctions.PartySharedFunctions_C.GetColorFromPing // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1b42740
	void GetQueueInfoText(struct UGameModeUIData* GameModeUIData, struct UMatchmakingQueueDataAsset* QueueDataAsset, struct UObject* __WorldContext, struct FText& QueueInfoText); // Function PartySharedFunctions.PartySharedFunctions_C.GetQueueInfoText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CheckPartyMembersEligibility(struct UPartyModel* Model, struct UObject* __WorldContext, bool& AreAnyMembersIneligible, struct TArray<struct FString>& IneligibleMembers); // Function PartySharedFunctions.PartySharedFunctions_C.CheckPartyMembersEligibility // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CheckCustomTeamsFull(struct UPartyModel* Model, struct UObject* __WorldContext, bool& IsFull); // Function PartySharedFunctions.PartySharedFunctions_C.CheckCustomTeamsFull // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CheckOtherPartyMembersSession(struct UPartyModel* Model, struct FString MySubject, struct UObject* __WorldContext, bool& AreAnyMembersBusy, struct TArray<struct FString>& BusyMembers); // Function PartySharedFunctions.PartySharedFunctions_C.CheckOtherPartyMembersSession // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
	void CheckPartySize(struct UPartyModel* Model, struct UObject* __WorldContext, bool& IsPartyTooLarge, bool& IsPartyTooSmall, int32_t& PartySizeRequirement); // Function PartySharedFunctions.PartySharedFunctions_C.CheckPartySize // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1b42740
};

