// Class BlueprintComponentReference.BlueprintComponentReferenceLibrary
// Size: 0x30 (Inherited: 0x30)
struct UBlueprintComponentReferenceLibrary : UBlueprintFunctionLibrary {

	void TryGetReferencedComponent(struct FBlueprintComponentReference& Reference, struct AActor* Actor, struct UActorComponent* Class, enum class EComponentSearchResult& Result, struct UActorComponent*& Component); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.TryGetReferencedComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x5529c30
	bool Set_ContainsComponent(struct TSet<struct FBlueprintComponentReference>& TargetSet, struct UActorComponent* ItemToFind); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Set_ContainsComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5528040
	bool NotEqual_ComponentReference(struct FBlueprintComponentReference& A, struct FBlueprintComponentReference& B); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.NotEqual_ComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x55288b0
	bool Map_FindComponent(struct TMap<int32_t, int32_t>& TargetMap, struct UActorComponent* Component, int32_t& Value); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Map_FindComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5527b50
	bool IsValidComponentReference(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.IsValidComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5528d90
	bool IsNullComponentReference(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.IsNullComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5528eb0
	void InvalidateComponentReference(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.InvalidateComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x5528c90
	void GetSetReferencedComponents(struct TSet<struct FBlueprintComponentReference>& References, struct AActor* Actor, struct UActorComponent* Class, struct TSet<struct UActorComponent*>& Components); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.GetSetReferencedComponents // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x5528fd0
	void GetReferencedComponents(struct TArray<struct FBlueprintComponentReference>& References, struct AActor* Actor, struct UActorComponent* Class, bool bKeepNulls, struct TArray<struct UActorComponent*>& Components); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.GetReferencedComponents // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x55294a0
	bool GetReferencedComponent(struct FBlueprintComponentReference& Reference, struct AActor* Actor, struct UActorComponent* Class, struct UActorComponent*& Component); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.GetReferencedComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5529850
	bool EqualEqual_ComponentReference(struct FBlueprintComponentReference& A, struct FBlueprintComponentReference& B); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.EqualEqual_ComponentReference // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5528aa0
	struct FString Conv_ComponentReferenceToString(struct FBlueprintComponentReference& Reference); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Conv_ComponentReferenceToString // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5528740
	bool Array_ContainsComponent(struct TArray<struct FBlueprintComponentReference>& TargetArray, struct UActorComponent* ItemToFind); // Function BlueprintComponentReference.BlueprintComponentReferenceLibrary.Array_ContainsComponent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable|BlueprintPure) // @ game+0x5528510
};

