// BlueprintGeneratedClass SocialFunctionLibrary.SocialFunctionLibrary_C
// Size: 0x30 (Inherited: 0x30)
struct USocialFunctionLibrary_C : UBlueprintFunctionLibrary {

	void Show Unblock Confirmation Modal(struct FString PlayerSubject, struct FString PlayerPrefix, struct FString PrefixSeparator, struct FString PlayerName, struct FString PlayerTag, struct UObject* __WorldContext, struct UWBP_Screen_GenericConfirmation_C*& ConfirmationWidget); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.Show Unblock Confirmation Modal // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void Show Block Confirmation Modal(struct FString PlayerSubject, struct FString PlayerPrefix, struct FString PrefixSeparator, struct FString PlayerName, struct FString PlayerTag, struct UObject* __WorldContext, struct UWBP_Screen_GenericConfirmation_C*& ConfirmationWidget); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.Show Block Confirmation Modal // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void GetFormattedRiotID(struct FString Player Name, struct FString Player Tag, struct UObject* __WorldContext, struct FText& Return Value); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.GetFormattedRiotID // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1af5410
	void PartyErrorCodeToPlayerMessage(enum class EPartyErrorEnum PartyErrorCode, enum class EAresSocialPartyErrorSource PartyErrorSource, struct FText DefaultMessage, struct UObject* __WorldContext, struct FText& Message); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.PartyErrorCodeToPlayerMessage // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1af5410
	void ShowSocialConfirmationModal(struct FText Title, struct FText Description, struct FText ConfirmButtonText, struct FText CancelButtonText, struct UConfirmModalCallbacks* CallbackInfo, struct UObject* __WorldContext, struct UWBP_Screen_GenericConfirmation_C*& MenuStackManagerScreen); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.ShowSocialConfirmationModal // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void HandleSocialError(struct FText Title, struct FText Message, struct FText ButtonText, bool SendChatMessageOnPC, struct TArray<struct FGameplayTag>& ModalContext, struct UObject* __WorldContext); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.HandleSocialError // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void ShowDesktopUnblockConfirmationModal(struct UObject* WorldContextObject, struct FString PlayerPrefix, struct FString PlayerName, struct FString PlayerTag, struct UObject* __WorldContext, struct UConfirmationModal_C*& ConfirmationModal); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.ShowDesktopUnblockConfirmationModal // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void ShowDesktopBlockConfirmationModal(struct UObject* WorldContextObject, struct FString PlayerPrefix, struct FString PrefixSeparator, struct FString PlayerName, struct FString PlayerTag, struct UObject* __WorldContext, struct UConfirmationModal_C*& ConfirmationModal); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.ShowDesktopBlockConfirmationModal // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void Show Social Player Context Menu As Side Screen(struct UObject* WorldContext, struct FString PlayerSubject, struct FString MatchID, struct FGuid OverridePlayerCardID, struct UAresContextMenuItemFilterDataAsset* ItemFilter, struct UObject* __WorldContext); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.Show Social Player Context Menu As Side Screen // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
	void ShowSocialErrorModal(struct UObject* World Context, struct FText Title, struct FText Description, struct FText ButtonText, struct UObject* __WorldContext); // Function SocialFunctionLibrary.SocialFunctionLibrary_C.ShowSocialErrorModal // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1af5410
};

